### ISSUE TITLE
How can you connect to main net?

### ISSUE THREAD

**Issue by dorufoaltin** [bugbytesinc/Hashgraph#218]
Hi, 

I'm trying to connect to the main net to do a simple GetAccountBalance from an account, and I can't find a way to properly connect to the main net. 

I'm trying with this code: 
![image](https://github.com/bugbytesinc/Hashgraph/assets/6756850/93d46162-08b2-4cdc-8bc5-2ed05c5fe37e)

I assume the uri provided is wrong, but I can't find the proper one, and the current [documentation](https://bugbytesinc.github.io/Hashgraph/tutorials/crypto/balance.html) is out of date. 

Can you point me to the right direction?
Thanks!

**Comment by bugbytesinc** [comment]
A `Gateway` is a paring of a **hedera gossip node's** Wallet (0.0.3) and a gRPC endpoint (http://34.239.82.6:50211).  The specific error above suggests that it is the constructor of the `Uri` object, the string does not include the scheme (in this case `http`).  Yes you are correct that the documentation is out of date, its a perennial problem for FOSS that does not have a deep pocketed sponsor (such as this project)  The code above looks like 10 Beta 4 (I think 10 introduced the new constructor for Gateway)

**mainnet.hedera.com** is not a gossip node endpoint, there are two places you can get a list of mainnet gossip nodes:

Hedera's Documentation (note, they list more IP addresses than appear in the second way, ymmv):

https://docs.hedera.com/hedera/networks/mainnet/mainnet-nodes

You can also get the current list of gossip nodes as a mirror node knows them:

https://mainnet-public.mirrornode.hedera.com/api/v1/network/nodes

A third way to get the gateway is to use the extension method `MirrorRestClient.GetActiveGatewaysAsync` which returns a dictionary of `Gateway` objects and their latest response times to a simulated ping.  [Note that method may not be documented yet, the code, still being beta, is in flux and subject to change]  To use that you will first need to create a `MirrorRestClient` pointed to a mirror node of your choosing.  This approach is turning out to be the preferred way to boostrap a process and automatically connect to working Gossip Nodes.
