### ISSUE TITLE
Endorsement's Equals method not corret

### ISSUE THREAD

**Issue by janheski** [bugbytesinc/Hashgraph#89]
https://github.com/bugbytesinc/Hashgraph/blob/1fbcd4f242fb4d219dfb871bed4f01c96d83ca83/src/Hashgraph/Endorsement.cs#L183

This looks like it wouldn't work, it should be like
```
var otherList = (Endorsement[])other._data;
```

**Comment by bugbytesinc** [comment]
Yes indeed, thankyou for catching that!

**Comment by bugbytesinc** [comment]
Hi @janheski does the PR look good?  (apologies, I haven't set up formal PR reviews quite right in this project yet)

**Comment by janheski** [comment]
Great, thanks!
